// src/config/order-config.js
export const MENU_PHOTO_URL = 'https://drive.google.com/uc?export=download&id=1Nh-u0g1XTdKnKwCFMBKem8yttpa1dybN';
export const WELCOME_MESSAGE = "Buenas tardes ☺️ ¡Hola! 😊 Soy el asistente de Restaurante Cocina Casera.\nCada almuerzo cuesta $13.000 (sin sopa: $12.000).\n🍽️ ¿Cuántos almuerzos quieres hoy?\nPuedes decir: '1', 'tres', 'dos almuerzos', etc.";
export const CLOSED_MESSAGE = "Estamos cerrados ahora. ⏰ Horario: 7:00 am - 4:00 pm, lunes a sábado. ¡Te esperamos pronto! 😊";
export const PAYMENT_NUMBER = '3138505647';
export const CONVERSATION_TIMEOUT = 30 * 60 * 1000;

export const SOUP_MENU = "🍲 ¿Sancocho de pescado, sopa del día o prefieres?\n1. Huevo - frito\n2. Papa a la francesa\n3. Solo bandeja ($12.000)\n¿Qué eliges?";
export const PROTEIN_MENU = "🍗 ¿Qué proteína quieres? (Ej: res, cerdo, pechuga gratinada, mojarra)";
export const PRINCIPLE_MENU = "🥗 ¿Qué principio deseas? (Puedes elegir más de uno, ej: frijol, pasta, lenteja)";
export const DRINK_MENU = "🥤 ¿Qué bebida deseas?\n1. Limonada de panela\n2. Jugo - Natural del día";

export const VALID_SOUPS = ['sancocho de pescado','crema de ahuyama','Sopa del dia', 'sopa de avena', 'sopa de mute', 'sopa de arroz', 'sopa de ajiaco', 'sopa de cuchuco de maiz', 'sopa de pasta', 'sopa de patacon', 'sopa de colicero', 'sopa de cuchuco de trigo con espinazo de cerdo', 'sopa de verduras', 'sopa de cuchuco de maiz pintado', 'sopa de cebada perlada', 'cuchuco de trigo', 'sopa de mondongo', 'sopa campesina', 'sopa de lentejas', 'sopa de mazamorra de maiz pintado', 'huevo', 'plátano', 'papa a la francesa', 'solo bandeja', 'sin sopa'];
export const VALID_PROTEINS = ['res asada','Res en salsa champinion', 'cerdo asado','higado encebollado', 'pechuga gratinada', 'chuleta valluna apanada', 'mojarra', 'cachama sudada o frita', 'res','pierna dorada', 'cerdo', 'pechuga asada', 'milanesa de pollo apanada', 'albóndigas sudadas', 'pierna pernil en salsa ranchera', 'pierna pernil a la jardinera', 'pierna pernil en miel mostaza', 'res en salsa ranchera', 'lomo apanado', 'chuleta ahumada en salsa BBQ', 'hígado encebollado', 'carne en bistec', 'sobrebarriga en salsa criolla', 'pierna pernil en salsa de champiñón', 'bagre en sudado', 'entero de pierna pernil con mazorca, arracacha, papa, arroz y ensalada', 'pechuga en miel mostaza', 'murillo sudado', 'lomo en salsa grillé', 'pechuga en salsa de champiñón', 'bagre en salsa', 'sobrebarriga asada', 'costillitas ahumadas en salsa BBQ', 'pata sudada', 'carne en salsa de champiñón', 'lomo en salsa hawaiana', ];
export const VALID_PRINCIPLES = ['frijol', 'arveja', 'garbanzo', 'lenteja', 'pasta', 'ahuyama', 'macarrones', 'spagetti', 'pepino guisado', 'acelga guisada', 'habichuela guisada', 'arroz oriental', 'espaguetti en salsa boloñesa', 'arroz paisa, papa a la francesa, ensalada dulce no viene con proteina porque el arroz ya la tiene incorporada', 'calabacin guisado', 'spagetti guisado', 'guatila guisada', 'arroz tres carnes ya la proteina esta incorporada, papa a la francesa y ensalada dulce', 'brocoli en salsa blanca o guisado', 'ensalada rusa', 'arroz con pollo ya la proteina esta incorporada, papa a la francesa y ensalada', 'spagetti a la boloñesa', 'verdura salteada', 'macarrones en salsa carbonara', 'espinaca guisada', 'goulash de verduras', 'macarrones guisados'];
export const VALID_DRINKS = ['limonada de panela', 'mango', 'tomate de árbol', 'avena', 'jugo', 'maracuyá', 'lulo', 'mora', 'guayaba', 'te frío', 'fresa', 'feijoa', 'kuruba'];
export const VALID_PAYMENTS = ['efectivo', 'nequi', 'daviplata'];
